export const LOAD_INITIAL_IMAGES = {
  REQUEST: "LOAD_INITIAL_IMAGES_REQUEST",
  LOADING: "LOAD_INITIAL_IMAGES_LOADING",
  SUCCESS: "LOAD_INITIAL_IMAGES_SUCCESS",
  ERROR: "LOAD_INITIAL_IMAGES_ERROR",
};
